### ISSUE TITLE
source doesnt use the custom collision mesh

### ISSUE THREAD

**Issue by shadept-GitHub** [theanine3D/source-engine-collision-tools#7] opened 2024-06-20 14:56 UTC
this tool doesnt work. im trying to port a map from another game and every time i try to import a model into source thats a chunk of the map the collision mesh is discarded and i tried using crowbar to see the log manually and it still wont work. its a map from minecraft but since the creator of that one tool that converts minecraft worlds to source has abandoned their project and the tool doesnt work i have to resort to making the map into models. i tried adding a solidify modifier to the map geometry and then making a collision mesh based on that but it wouldnt work either, source just disregards the collision mesh and makes its own without any reason why in the log.
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/65095770/8e36e64a-411e-4c9d-af59-b065e6a89b9b)
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/65095770/93f650f3-51dc-4e3c-912b-10cafd77e210)

**Comment by theanine3D** [comment] 2024-06-20 15:53
Please post the QC file that you're compiling, and possibly the Blender file, so I can see what the problem is.

Note that Source will always, by default, try to merge all hulls together into a single convex hull, unless you have set up the QC file correctly. This is normal, expected behavior on the compiler's part. It doesn't mean the Blender addon isn't working. You need to make sure you have $concave in your $collisionmodel command in the QC file, like in the example below, to force the compiler to _not_ merge the hulls into a single one.,

`$collisionmodel "_name_of_collision_mesh_.smd"`
`{`
`	$concave`
`	$automass`
`}`

However, if you have _more than_ 32 hulls in that single collision mesh, the compiler will still merge them all into one anyway, even if you included $concave in the QC file. In that case, you will need to split up the mesh into multiple parts. The addon has a button that will do it for you.

**Comment by shadept-GitHub** [comment] 2024-06-20 22:36
> If you have more than 32 hulls in that single mesh, the compiler will merge them all anyway, even if you included $concave in the QC file. In that case, you will need to split up the mesh into multiple parts. The addon has a button that will do it for you.

see, this is my problem. when i try to split the collision mesh my blender freezes and it takes 2 hours to split the collision mesh. and even then, how am i supposed to use that? use them as separate static props?

**Comment by theanine3D** [comment] 2024-06-20 22:40
Looking at your screenshot above I can see a ton of hulls that should be merged together. Your mesh is likely just too complex if the Split Up button is freezing Blender. Please post the Blender file so I can see exactly what's going on. When you press the Force Convex button, what is the amount of hulls that it tells you?

And as for the split-up parts, the Generate QC button will generate QC files for all of the split up parts, and then you can compile all of them easily with Crowbar. Then after compiling them, you can use the Update VMF button to add them automatically to your VMF. However, the first part (part_000) needs to be added first, manually, by you in Hammer. The Update VMF button will look for any entity (ie. prop_static) that has part_000 assigned to it, and it will insert all of the other parts in the same position as part_000 (with the same entity settings.)

**Comment by shadept-GitHub** [comment] 2024-06-21 10:46
heres the .blend file
[maptest.zip](https://github.com/user-attachments/files/15926530/maptest.zip)
im not sure about force convex hull because it also freezes up blender for a while and i always glanced over it unfortunately. i also cant make my map one big model as there are more than 32 materials for every part but if i can at least automate the collision then i could handle the map reference mesh myself i suppose. i use [sourceops](https://github.com/bonjorno7/SourceOps) for compiling models by the way but i do also have crowbar. its just more convient to use sourceops for me.

**Comment by theanine3D** [comment] 2024-06-21 18:41
The Force Convex Hull operator is probably the fastest operator in the whole addon. If even this button is making Blender lag for you, you definitely need to reduce the complexity of the collision mesh first.

I opened up your Blender file, and sure enough, after running Force Convex Hulls on it, I got this result:
![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/97663e5b-34b0-4c9f-b48d-e0b19daef320)

That is an extremely excessive amount of hulls. You should not be going above 100-300 (even 300 is excessive, but still technically usable if you split it up first.) Note that my addon is meant to be used as a starting point - you should still be cleaning up the resulting generated collision afterward. And this mesh direly needs it. Up until I opened your Blender file I had never encountered a situation where the Force Convex Button actually lagged, but it lagged on your collision. So your collision needs fixing.

You can easily merge a ton of these together, very quickly, manually, in Edit Mode. Follow these steps:
1) Go into Edit Mode with the Tab key
2) Press the Z key to go into Wireframe mode
3) Use the C key to enable circle select mode, then start highlighting sections of hulls that could be merged together without changing the overall shape of the whole collision. See example below:

![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/5e18ad26-ceaa-4edc-a869-7b93f55d7577)

After highlighting these faces, press **Ctrl + L** to highlight the entire hull pieces connected to those faces. Then, use the Convex Hull operator, which you can find in the Mesh menu (or press F3/Spacebar and search for "Convex Hull").

![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/fb75ea2a-6334-400e-abf0-5e4f47c6f8f5)

After doing that, all of those hulls will be merged together, forming only a single hull and significantly reducing the hull count.

![image](https://github.com/theanine3D/source-engine-collision-tools/assets/88953117/823473cc-8b2d-4c8b-b769-c180ef3ac09e)

Repeat these steps for the rest of the collision mesh, and try to get the collision mesh to a total of under 100 hulls. Given how simple the shapes in your scene are (they're just a bunch of blocks and very flat pieces of ground), you can definitely reduce this to something well below 100 hulls. Use the Force Convex button to keep counting how many you have so far. When you reach the point where the Force Convex button no longer freezes Blender, you've probably got something usable. However, remember that any hull count above 32 will still require splitting up the mesh first, via the Split Up Collision Mesh button. As long as your hull count is above 32, Source will keep merging all hulls into a single one.

I will be closing this now as I've confirmed the issue is not a bug or issue with the addon itself, but an issue with your collision.

**Closed as completed by theanine3D** 2024-06-21 18:41 UTC

**Comment by shadept-GitHub** [comment] 2024-06-23 21:13
im not sure how to really approach this. it seems tedious and force convex ends up messing up all my work from when i merged some parts of it.
